### ISSUE TITLE
waffle

### ISSUE THREAD

**Issue by CristianNe** [axelarnetwork/axelar-local-gmp-examples#20]
Hello 👋
I'm setting up an axelar test environment and using this repo as orientation. However, when I try to run `npm run build` on my environment, it returns `sh: 1: waffle: not found`. 

I have an identical `package.json` and `waffle.json` at root
![image](https://user-images.githubusercontent.com/28632299/168646926-eeae8fb9-9bca-4b2e-9ba5-4c20df92614c.png)

I tried substituting waffle with `ethereum-waffle`  and running `rm -rf bulid && waffle waffle.json` but to no avail.

Am I overlooking something? I'd appreciate any feedback.

**Comment by ggutoski** [comment]
Reproduced on my machine.  @Foivos @npty Can you please take a look?
